spring.application.name: zuul-api-gateway
server.port: ${service.port}

zuul:
    host:
        socket-timeout-millis: ${timeout.millis}
    sensitive-headers:   
    routes:
        product-service:
            path: ${context.path.product}/**
        customer-service:
            path: ${context.path.customer}/**
        order-service:
            path: ${context.path.order}/**
        eshop-service:
            path: ${context.path.eshop}/**