version: '3'


networks:
    elwannw:


volumes:
    mongodb-datavolume:
    mariadb-datavolume:
    postgresdb-datavolume:


services:

#-------------------  Databases section  -----------------------------

    mongo-db:
        image: mongo
        container_name: mongo-db
        environment:
            MONGO_INITDB_ROOT_USERNAME: melwan
            MONGO_INITDB_ROOT_PASSWORD: melwan123
            MONGO_INITDB_DATABASE: customers_db
        volumes:
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
            - mongodb-datavolume:/data/db
        ports:
            - 27020:27017
        networks:
            - elwannw

    maria-db:
        image: mariadb:latest
        container_name: maria-db
        environment:
            MYSQL_ROOT_PASSWORD: 'd@ysnetisalat'
            MYSQL_DATABASE: 'products_db'
            MYSQL_USER: 'melwan'
            MYSQL_PASSWORD: 'melwan123'
        ports:
            - '3366:3306'
        command: --init-file /data/application/init.sql
        volumes:
            - mariadb-datavolume:/var/lib/mysql
            - ./maria-init.sql:/data/application/init.sql
        networks:
            - elwannw

    postgres-db:
        image: postgres:latest
        container_name: postgres-db
        environment:
            - POSTGRES_DB=orders_db
            - POSTGRES_USER=melwan
            - POSTGRES_PASSWORD=melwan123
        ports:
            - '5445:5432'
        volumes:
            - postgresdb-datavolume:/var/lib/postgresql/data
        networks:
            - elwannw

#-------------------  Technical Services section  -----------------------------

    zipkin-server:
        image: openzipkin/zipkin
        container_name: zipkin-server
        ports:
            - "9411:9411"
        networks:
            - elwannw

    eureka-discovery-service:
        build: ../../tech_eureka-discovery-service
        image: mostafaelwan/mcsv-smpl-eureka-server:latest
        container_name: eureka-discovery-service
        ports:
            - 8765:8765
        networks:
            - elwannw

    config-server:
        build: ../../tech_cloud-config-server
        image: mostafaelwan/mcsv-smpl-config-server:latest
        container_name: config-server
        depends_on:
            - eureka-discovery-service
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
        ports:
            - 8888:8888
        volumes:
            - ./config-server/config:/app/config
        networks:
            - elwannw

    admin-server:
        build: ../../tech_spring-admin-server
        image: mostafaelwan/mcsv-smpl-admin-server:latest
        container_name: admin-server
        depends_on:
            - config-server
        command: ["./wait-for.sh", "config-server:8888", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
        ports:
            - 9999:9999
        networks:
            - elwannw

    zuul-proxy:
        build: ../../tech_zuul-api-gateway
        image: mostafaelwan/mcsv-smpl-zuul-proxy:latest
        container_name: zuul-proxy
        depends_on:
            - config-server
        command: ["./wait-for.sh", "config-server:8888", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
        ports:
            - 8080:8080
        networks:
            - elwannw


#-------------------  Business Services section  -----------------------------

    customer-service:
        build: ../../bsns_customer-service
        image: mostafaelwan/mcsv-smpl-customer-service:latest
        container_name: customer-service
        depends_on:
            - mongo-db
            - config-server
        command: ["./wait-for.sh", "admin-server:9999", "--", "./wait-for.sh", "mongo-db:27017", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
            - ZIPKIN_SERVER_IP_PORT=zipkin-server:9411
        ports:
            - 8092:8092
        networks:
            - elwannw

    product-service:
        build: ../../bsns_product-service
        image: mostafaelwan/mcsv-smpl-product-service:latest
        container_name: product-service
        depends_on:
            - maria-db
            - config-server
        command: ["./wait-for.sh", "admin-server:9999", "--", "./wait-for.sh", "maria-db:3306", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
            - ZIPKIN_SERVER_IP_PORT=zipkin-server:9411
        ports:
            - 8091:8091
        networks:
            - elwannw

    order-service:
        build: ../../bsns_order-service
        image: mostafaelwan/mcsv-smpl-order-service:latest
        container_name: order-service
        depends_on:
            - postgres-db
            - config-server
        command: ["./wait-for.sh", "admin-server:9999", "--", "./wait-for.sh", "postgres-db:5432", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
            - ZIPKIN_SERVER_IP_PORT=zipkin-server:9411
        ports:
            - 8093:8093
        networks:
            - elwannw

    eshop-service:
        build: ../../bsns_eshop-service
        image: mostafaelwan/mcsv-smpl-eshop-service:latest
        container_name: eshop-service
        depends_on:
            - customer-service
            - product-service
            - order-service
        command: ["./wait-for.sh", "customer-service:8092", "--", "./wait-for.sh", "product-service:8091", "--", "./wait-for.sh", "order-service:8093", "--", "java","-jar","app.jar"]
        environment:
            - EUREKA_SERVER_IP_PORT=eureka-discovery-service:8765
            - ZIPKIN_SERVER_IP_PORT=zipkin-server:9411
        ports:
            - 8090:8090
        networks:
            - elwannw
